import bcrypt from 'bcryptjs';
import { DataTypes } from '../types/DataTypes';


const data: DataTypes = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Men’s Leather Jacket',
      category: 'Jackets',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1638408201374-ff177f17e7a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDh8fE1lbiVFMiU4MCU5OXMlMjBMZWF0aGVyJTIwSmFja2V0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 199,
      brand: 'Macy',
      rating: 4.8,
      numReviews: 28,
      countInStock: 10,
      isFeatured: true,
      description: 'This men’s leather jacket is made of high-quality leather and has a comfortable fit. It features a zip-up closure and two pockets on the front. Perfect for any occasion!',
    },
    {
      name: 'Women’s Running Shoes',
      category: 'Shoes',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8d29tZW4lMjBydW5uaW5nJTIwc2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 89,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 37,
      countInStock: 5,
      isFeatured: true,
      description: 'These women’s running shoes are designed for comfort and style. The breathable mesh upper keeps your feet cool and dry, while the cushioned sole provides support and comfort for long runs.',
    },
    {
      name: 'Organic Cotton T-Shirt',
      category: 'T-Shirts',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8T3JnYW5pYyUyMENvdHRvbiUyMFQlMjBTaGlydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 29,
      brand: 'H&M',
      rating: 3.9,
      numReviews: 21,
      countInStock: 15,
      isFeatured: false,
      description: 'This organic cotton t-shirt is a must-have for anyone who cares about the environment. It’s soft, comfortable, and made of 100% organic cotton. Perfect for a casual day out!',
    },
    {
      name: 'Travel Backpack',
      category: 'Backpacks',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1555337159-d399aaa99955?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8VHJhdmVsJTIwQmFja3BhY2t8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 149,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 45,
      countInStock: 8,
      isFeatured: false,
      description: 'This travel backpack is perfect for your next adventure. It has plenty of pockets to keep your essentials organized, and the comfortable straps make it easy to carry. Plus, it’s made of durable materials to withstand any weather condition.',
    },
    {
      name: 'Men’s Slim Fit Suit',
      category: 'Suits',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1554774853-719586f82d77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fE1lbiVFMiU4MCU5OXMlMjBTbGltJTIwRml0JTIwU3VpdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 249,
      brand: 'Calvin Klein',
      rating: 4.9,
      numReviews: 87,
      countInStock: 8,
      isFeatured: false,
      description: 'Look sharp and stylish in this men’s slim fit suit from Calvin Klein. Made with high-quality materials, this suit is perfect for any formal occasion. The slim fit design ensures a modern and sleek silhouette, while the comfortable fabric allows for easy movement and all-day wear.'
    },
    {
      name: 'Stylish Jacket',
      category: 'Jackets',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fFN0eWxpc2glMjBKYWNrZXQlMjBtZW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 120,
      brand: 'Sleekwear',
      rating: 4.6,
      numReviews: 27,
      countInStock: 10,
      isFeatured: false,
      description: `The Stylish Jacket is perfect for any occasion. It's made with premium materials and features a comfortable fit that's both stylish and functional. Whether you're out for a night on the town or just running errands, this jacket has got you covered.`
    },
    {
      name: 'Sporty Sneakers',
      category: 'Shoes',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1613743069803-c36101c1de01?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fFNwb3J0eSUyMFNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 90,
      brand: 'Flexx',
      rating: 3.9,
      numReviews: 15,
      countInStock: 5,
      isFeatured: false,
      description: `Get ready to hit the gym or the streets with these Sporty Sneakers. They're made with a lightweight design and durable materials to keep your feet comfortable and supported during any activity. These sneakers also feature a stylish design that's perfect for any casual look.`
    },
    {
      name: 'Classic T-Shirt',
      category: 'Shirts',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1484516396415-4971641de8e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fENsYXNzaWMlMjBUJTIwU2hpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 35,
      brand: 'Casual Comfort',
      rating: 4.2,
      numReviews: 21,
      countInStock: 30,
      isFeatured: false,
      description: `The Classic T-Shirt is a must-have for any wardrobe. It's made with soft, breathable fabric that's comfortable to wear all day long. This shirt features a simple, yet stylish design that's perfect for any casual occasion.`
    },
    {
      name: 'Stylish Watch',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1619134778706-7015533a6150?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fFN0eWxpc2glMjBXYXRjaHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 150,
      brand: 'Lux Accessoires',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      isFeatured: false,
      description: 'Add a touch of sophistication to your outfit with this Stylish Watch from Lux Accessoires. Made with high-quality materials, it features a sleek design with a comfortable leather strap. The watch also has a durable stainless steel case and a water-resistant finish, making it perfect for everyday wear.'
    },
    {
      name: 'Vintage Sunglasses',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1505157836763-ac50a6b98076?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fFZpbnRhZ2UlMjBTdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 50,
      brand: 'Retro Shades',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      isFeatured: false,
      description: `Add a touch of vintage style to your look with these Vintage Sunglasses. They're made with high-quality materials and feature a classic design that never goes out of style. These sunglasses also provide excellent protection from the sun's harmful rays.`
    },
     {
      name: 'Men’s Leather Jacket',
      category: 'Jackets',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1638408201374-ff177f17e7a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDh8fE1lbiVFMiU4MCU5OXMlMjBMZWF0aGVyJTIwSmFja2V0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 199,
      brand: 'Macy',
      rating: 4.8,
      numReviews: 28,
      countInStock: 10,
      isFeatured: false,
      description: 'This men’s leather jacket is made of high-quality leather and has a comfortable fit. It features a zip-up closure and two pockets on the front. Perfect for any occasion!',
    },
    {
      name: 'Women’s Running Shoes',
      category: 'Shoes',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8d29tZW4lMjBydW5uaW5nJTIwc2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 89,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 37,
      countInStock: 5,
      isFeatured: false,
      description: 'These women’s running shoes are designed for comfort and style. The breathable mesh upper keeps your feet cool and dry, while the cushioned sole provides support and comfort for long runs.',
    },
    {
      name: 'Organic Cotton T-Shirt',
      category: 'T-Shirts',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8T3JnYW5pYyUyMENvdHRvbiUyMFQlMjBTaGlydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 29,
      brand: 'H&M',
      rating: 3.9,
      numReviews: 21,
      countInStock: 15,
      isFeatured: false,
      description: 'This organic cotton t-shirt is a must-have for anyone who cares about the environment. It’s soft, comfortable, and made of 100% organic cotton. Perfect for a casual day out!',
    },
    {
      name: 'Travel Backpack',
      category: 'Backpacks',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1555337159-d399aaa99955?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8VHJhdmVsJTIwQmFja3BhY2t8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 149,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 45,
      countInStock: 8,
      isFeatured: false,
      description: 'This travel backpack is perfect for your next adventure. It has plenty of pockets to keep your essentials organized, and the comfortable straps make it easy to carry. Plus, it’s made of durable materials to withstand any weather condition.',
    },
    {
      name: 'Men’s Slim Fit Suit',
      category: 'Suits',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1554774853-719586f82d77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fE1lbiVFMiU4MCU5OXMlMjBTbGltJTIwRml0JTIwU3VpdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 249,
      brand: 'Calvin Klein',
      rating: 4.9,
      numReviews: 87,
      countInStock: 8,
      isFeatured: false,
      description: 'Look sharp and stylish in this men’s slim fit suit from Calvin Klein. Made with high-quality materials, this suit is perfect for any formal occasion. The slim fit design ensures a modern and sleek silhouette, while the comfortable fabric allows for easy movement and all-day wear.'
    },
    {
      name: 'Stylish Jacket',
      category: 'Jackets',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fFN0eWxpc2glMjBKYWNrZXQlMjBtZW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 120,
      brand: 'Sleekwear',
      rating: 4.6,
      numReviews: 27,
      countInStock: 10,
      isFeatured: false,
      description: `The Stylish Jacket is perfect for any occasion. It's made with premium materials and features a comfortable fit that's both stylish and functional. Whether you're out for a night on the town or just running errands, this jacket has got you covered.`
    },
    {
      name: 'Sporty Sneakers',
      category: 'Shoes',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1613743069803-c36101c1de01?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fFNwb3J0eSUyMFNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 90,
      brand: 'Flexx',
      rating: 3.9,
      numReviews: 15,
      countInStock: 5,
      isFeatured: false,
      description: `Get ready to hit the gym or the streets with these Sporty Sneakers. They're made with a lightweight design and durable materials to keep your feet comfortable and supported during any activity. These sneakers also feature a stylish design that's perfect for any casual look.`
    },
    {
      name: 'Classic T-Shirt',
      category: 'Shirts',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1484516396415-4971641de8e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fENsYXNzaWMlMjBUJTIwU2hpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 35,
      brand: 'Casual Comfort',
      rating: 4.2,
      numReviews: 21,
      countInStock: 30,
      isFeatured: false,
      description: `The Classic T-Shirt is a must-have for any wardrobe. It's made with soft, breathable fabric that's comfortable to wear all day long. This shirt features a simple, yet stylish design that's perfect for any casual occasion.`
    },
    {
      name: 'Stylish Watch',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1619134778706-7015533a6150?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fFN0eWxpc2glMjBXYXRjaHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 150,
      brand: 'Lux Accessoires',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      isFeatured: false,
      description: 'Add a touch of sophistication to your outfit with this Stylish Watch from Lux Accessoires. Made with high-quality materials, it features a sleek design with a comfortable leather strap. The watch also has a durable stainless steel case and a water-resistant finish, making it perfect for everyday wear.'
    },
    {
      name: 'Vintage Sunglasses',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1505157836763-ac50a6b98076?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fFZpbnRhZ2UlMjBTdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 50,
      brand: 'Retro Shades',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      isFeatured: false,
      description: `Add a touch of vintage style to your look with these Vintage Sunglasses. They're made with high-quality materials and feature a classic design that never goes out of style. These sunglasses also provide excellent protection from the sun's harmful rays.`
    },
     {
      name: 'Men’s Leather Jacket',
      category: 'Jackets',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1638408201374-ff177f17e7a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDh8fE1lbiVFMiU4MCU5OXMlMjBMZWF0aGVyJTIwSmFja2V0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 199,
      brand: 'Macy',
      rating: 4.8,
      numReviews: 28,
      countInStock: 10,
      isFeatured: false,
      description: 'This men’s leather jacket is made of high-quality leather and has a comfortable fit. It features a zip-up closure and two pockets on the front. Perfect for any occasion!',
    },
    {
      name: 'Women’s Running Shoes',
      category: 'Shoes',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8d29tZW4lMjBydW5uaW5nJTIwc2hvZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 89,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 37,
      countInStock: 5,
      isFeatured: false,
      description: 'These women’s running shoes are designed for comfort and style. The breathable mesh upper keeps your feet cool and dry, while the cushioned sole provides support and comfort for long runs.',
    },
    {
      name: 'Organic Cotton T-Shirt',
      category: 'T-Shirts',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8T3JnYW5pYyUyMENvdHRvbiUyMFQlMjBTaGlydHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 29,
      brand: 'H&M',
      rating: 3.9,
      numReviews: 21,
      countInStock: 15,
      isFeatured: false,
      description: 'This organic cotton t-shirt is a must-have for anyone who cares about the environment. It’s soft, comfortable, and made of 100% organic cotton. Perfect for a casual day out!',
    },
    {
      name: 'Travel Backpack',
      category: 'Backpacks',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1555337159-d399aaa99955?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8VHJhdmVsJTIwQmFja3BhY2t8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 149,
      brand: 'The North Face',
      rating: 4.5,
      numReviews: 45,
      countInStock: 8,
      isFeatured: false,
      description: 'This travel backpack is perfect for your next adventure. It has plenty of pockets to keep your essentials organized, and the comfortable straps make it easy to carry. Plus, it’s made of durable materials to withstand any weather condition.',
    },
    {
      name: 'Men’s Slim Fit Suit',
      category: 'Suits',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1554774853-719586f82d77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fE1lbiVFMiU4MCU5OXMlMjBTbGltJTIwRml0JTIwU3VpdHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 249,
      brand: 'Calvin Klein',
      rating: 4.9,
      numReviews: 87,
      countInStock: 8,
      isFeatured: true,
      description: 'Look sharp and stylish in this men’s slim fit suit from Calvin Klein. Made with high-quality materials, this suit is perfect for any formal occasion. The slim fit design ensures a modern and sleek silhouette, while the comfortable fabric allows for easy movement and all-day wear.'
    },
    {
      name: 'Stylish Jacket',
      category: 'Jackets',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1514222709107-a180c68d72b4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fFN0eWxpc2glMjBKYWNrZXQlMjBtZW58ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 120,
      brand: 'Sleekwear',
      rating: 4.6,
      numReviews: 27,
      countInStock: 10,
      isFeatured: true,
      description: `The Stylish Jacket is perfect for any occasion. It's made with premium materials and features a comfortable fit that's both stylish and functional. Whether you're out for a night on the town or just running errands, this jacket has got you covered.`
    },
    {
      name: 'Sporty Sneakers',
      category: 'Shoes',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1613743069803-c36101c1de01?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fFNwb3J0eSUyMFNuZWFrZXJzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 90,
      brand: 'Flexx',
      rating: 3.9,
      numReviews: 15,
      countInStock: 5,
      isFeatured: true,
      description: `Get ready to hit the gym or the streets with these Sporty Sneakers. They're made with a lightweight design and durable materials to keep your feet comfortable and supported during any activity. These sneakers also feature a stylish design that's perfect for any casual look.`
    },
    {
      name: 'Classic T-Shirt',
      category: 'Shirts',
      gender:'woman',
      image: 'https://images.unsplash.com/photo-1484516396415-4971641de8e0?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fENsYXNzaWMlMjBUJTIwU2hpcnR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
      price: 35,
      brand: 'Casual Comfort',
      rating: 4.2,
      numReviews: 21,
      countInStock: 30,
      isFeatured: true,
      description: `The Classic T-Shirt is a must-have for any wardrobe. It's made with soft, breathable fabric that's comfortable to wear all day long. This shirt features a simple, yet stylish design that's perfect for any casual occasion.`
    },
    {
      name: 'Stylish Watch',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1619134778706-7015533a6150?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fFN0eWxpc2glMjBXYXRjaHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60',
      price: 150,
      brand: 'Lux Accessoires',
      rating: 4.5,
      numReviews: 8,
      countInStock: 10,
      isFeatured: true,
      description: 'Add a touch of sophistication to your outfit with this Stylish Watch from Lux Accessoires. Made with high-quality materials, it features a sleek design with a comfortable leather strap. The watch also has a durable stainless steel case and a water-resistant finish, making it perfect for everyday wear.'
    },
    {
      name: 'Vintage Sunglasses',
      category: 'Accessories',
      gender:'man',
      image: 'https://images.unsplash.com/photo-1505157836763-ac50a6b98076?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzZ8fFZpbnRhZ2UlMjBTdW5nbGFzc2VzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60',
      price: 50,
      brand: 'Retro Shades',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      isFeatured: true,
      description: `Add a touch of vintage style to your look with these Vintage Sunglasses. They're made with high-quality materials and feature a classic design that never goes out of style. These sunglasses also provide excellent protection from the sun's harmful rays.`
    }
  ],
  blogs: [
    {
      author: "John Smith",
      category: "travel",
      excerpt: "Discover the best hidden gems in Europe with our ultimate travel guide. From quaint towns to stunning natural landscapes, we've got you covered.",
      image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8dHJhdmVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Ultimate Guide to Hidden Gems in Europe",
      first_content: "Are you tired of visiting the same old tourist traps? Look no further than our ultimate guide to hidden gems in Europe. From charming towns to breathtaking natural wonders, we've scoured the continent to bring you the best of the best. Whether you're an avid hiker or a history buff, there's something for everyone on this list.",
      second_content: "Take a stroll through the picturesque streets of Giethoorn in the Netherlands, or marvel at the stunning Cliffs of Moher in Ireland. If you're looking for a more off-the-beaten-path adventure, explore the unique architecture of Riga, Latvia, or soak in the thermal waters of the Blue Lagoon in Iceland. With our guide, you'll discover a side of Europe that most tourists never see.",
      isFeatured: true
    },
    {
      author: "Jane Doe",
      category: "food",
      excerpt: "From mouthwatering pizza to indulgent gelato, Italian cuisine is known for its bold flavors and fresh ingredients. Get ready to discover the best Italian dishes you've ever tasted!",
      image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
      title: "A Food Lover's Guide to Italy",
      first_content: "If you're a food lover, there's no better destination than Italy. From pizza to pasta to gelato, this country is home to some of the world's most iconic dishes. But with so many options, where do you start? That's where we come in. Our guide will take you on a culinary journey through Italy, highlighting the best dishes in each region.",
      second_content: "Indulge in the rich flavors of Tuscany with a hearty bowl of ribollita, or savor the seafood specialties of Sicily with a plate of pasta alla norma. And of course, no trip to Italy is complete without trying the world-famous Neapolitan pizza. With our guide, you'll discover new flavors and culinary traditions that will leave your taste buds begging for more.",
      isFeatured: false
    },
    {
      author: "David Lee",
      category: "health",
      excerpt: "Whether you're looking to lose weight, build muscle, or simply improve your overall health, our fitness guide has everything you need to get started.",
      image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGhlYWx0aHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Ultimate Fitness Guide for Beginners",
      first_content: "Starting a new fitness routine can be overwhelming, especially if you're not sure where to begin. That's why we've created the ultimate fitness guide for beginners. Our guide covers everything from setting realistic goals to choosing the right workout plan for your needs.",
      second_content: "Learn how to fuel your body with healthy, nutritious foods, and discover the best exercises for building strength and endurance. Whether you prefer to work out at home or at the gym, our guide has plenty of tips and advice to help you reach your fitness goals. With our step-by-step plan, you'll be on your way to a healthier, happier you in no time.",
      isFeatured: true
    },
    {
      author: "Shannan Shapter",
      category: "fashion",
      excerpt: "Looking for the perfect gift for the men in your life this holiday season? Look no further than our great big list of gift ideas! From stylish clothing to cutting-edge gadgets, we've got you covered.",
      image: "https://images.unsplash.com/photo-1537832816519-689ad163238b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGZhc2hpb258ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
      title: "The Great Big List of Men’s Gifts for the Holidays",
      first_content: "If you're struggling to come up with gift ideas for the men in your life, you're not alone. It can be tough to find the perfect present that's both thoughtful and practical. That's why we've put together this great big list of gift ideas that are sure to impress. Whether you're shopping for your dad, brother, boyfriend, or husband, we've got you covered. From stylish clothing to cutting-edge gadgets, there's something for everyone on your list.",
      second_content: "So what are you waiting for? Start browsing our list of gift ideas today and find the perfect present for the men in your life. And don't forget to check out our expert tips and advice on how to choose the perfect gift. Happy shopping!",
      isFeatured: false,
    },
    {
      author: "David Chen",
      category: "technology",
      excerpt: "From smartphones to laptops, discover the latest and greatest tech products of the year. We’ve rounded up the top 5 products that are worth the investment.",
      image: "https://images.unsplash.com/photo-1512686096451-a15c19314d59?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dGVjaCUyMHByb2R1Y3RzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "Top 5 Must-Have Tech Products of the Year",
      first_content: "Are you a tech enthusiast looking for the latest and greatest gadgets? Look no further than our list of the top 5 must-have tech products of the year. From cutting-edge smartphones to powerful laptops, these products are worth the investment.",
      second_content: "We’ve tested and reviewed each product to ensure that they meet our high standards for quality and innovation. So whether you’re a gamer, a photographer, or simply looking for a device that can keep up with your busy lifestyle, these products are sure to impress.",
      isFeatured: true,
    },
    {
    author: "John Smith",
    category: "technology",
    excerpt: "Artificial intelligence is changing the world we live in. From self-driving cars to voice assistants, AI is transforming the way we interact with technology. But what does the future hold for this powerful technology? In this article, we explore the potential impact of AI on society and the economy.",
    image: "https://images.unsplash.com/photo-1591696331111-ef9586a5b17a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGFydGlmaWNpYWwlMjBpbnRlbGxpZ2VuY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    title: "The Future of AI: Opportunities and Challenges",
    first_content: "Artificial intelligence is no longer the stuff of science fiction. It is now a part of our daily lives, from the voice assistants on our smartphones to the algorithms that power our social media feeds. As AI continues to evolve, it has the potential to transform the world we live in. However, it also presents a number of challenges and risks.",
    second_content: "One of the key challenges of AI is the potential impact on employment. As machines become more intelligent, they may be able to perform tasks that were previously done by humans. This could lead to widespread job displacement and economic disruption. Additionally, there are concerns about the impact of AI on privacy, security, and civil liberties. As AI becomes more pervasive, it may become more difficult to protect our personal data and ensure that our rights are respected.",
    isFeatured: true,
    },
    {
      author: "Sara Lee",
      category: "food",
      excerpt: "Trying to eat healthier can be tough, but there are simple changes you can make to your diet that can have a big impact. In this article, we share our top tips for eating healthy, including incorporating more fruits and vegetables into your meals, choosing whole grains, and limiting processed foods.",
      image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Zm9vZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "10 Simple Tips for Eating Healthier",
      first_content: "If you're looking to improve your diet, start by making small changes. One easy way to eat healthier is to incorporate more fruits and vegetables into your meals. Aim for a variety of colors to get a range of nutrients. Another tip is to choose whole grains instead of refined grains, which are stripped of important nutrients.",
      second_content: "Processed foods are often high in salt, sugar, and unhealthy fats, so it's best to limit these foods as much as possible. Instead, try cooking at home more often and using fresh ingredients. And don't forget to stay hydrated! Drinking plenty of water is essential for good health.",
      isFeatured: true,
    },
    {
      author: "Maria Rodriguez",
      category: "travel",
      excerpt: "Traveling is one of life's great pleasures, but it can be expensive. In this article, we share our top tips for traveling on a budget, including choosing affordable destinations, traveling during the off-season, and using rewards programs to save money on flights and hotels.",
      image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      title: "How to Travel on a Budget: Tips and Tricks",
      first_content: "One of the easiest ways to save money on travel is to choose affordable destinations. There are plenty of beautiful places to visit that won't break the bank, such as Southeast Asia, Eastern Europe, and Central America. Another tip is to travel during the off-season, when prices are typically lower and crowds are thinner.",
      second_content: "To save money on flights and hotels, consider signing up for rewards programs. Many airlines and hotel chains offer loyalty programs that allow you to earn points or miles that can be redeemed for free or discounted travel. And don't forget to be flexible with your travel plans - by being open to different dates and times, you may be able to find better deals.",
      isFeatured: false,
    },
    {
      author: "David Brown",
      category: "business",
      excerpt: "Leadership is a critical component of success in business. In this article, we explore the qualities of effective leaders, including the ability to inspire and motivate others, the willingness to take risks, and the capacity for strategic thinking.",
      image: "https://images.unsplash.com/photo-1664575600796-ffa828c5cb6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGJ1c2luZXNzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Qualities of Effective Leaders",
      first_content: "Effective leaders have a number of key qualities that set them apart from others. One of the most important is the ability to inspire and motivate others. Great leaders are able to communicate their vision and get others excited about working toward a common goal. They are also willing to take risks and make bold decisions, even in the face of uncertainty.",
      second_content: "Another important quality of effective leaders is the capacity for strategic thinking. They are able to see the big picture and develop a long-term plan for success. And they are not afraid to make tough decisions or pivot when necessary. Finally, great leaders lead by example, setting a high standard for themselves and their team.",
      isFeatured: false,
    },
    {
      author: "Emma Davis",
      category: "travel",
      excerpt: "If you're looking for an unforgettable beach vacation in Southeast Asia, you're in luck. Our top 10 beaches to visit will take you to some of the most stunning destinations in the region. From pristine white sands to crystal clear waters, these beaches offer the perfect getaway for any traveler.",
      image: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYXZlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "Top 10 Beaches to Visit in Southeast Asia",
      first_content: "Our top pick for the best beach in Southeast Asia is the stunning Maya Bay in Thailand. With its clear turquoise waters and towering limestone cliffs, it's a true paradise for beachgoers. Other highlights include the gorgeous beaches of Bali, Indonesia, where you can surf, swim, and soak up the sun, and the secluded shores of Palawan, Philippines, which offer a peaceful escape from the crowds.",
      second_content: "If you're looking for something off the beaten path, consider visiting the beaches of Koh Rong, Cambodia, which are known for their untouched natural beauty. Or head to the island of Phu Quoc in Vietnam, where you can relax on the quiet beaches and explore the vibrant local culture. No matter where you choose to go, Southeast Asia is home to some of the world's most beautiful beaches, and we're excited to share our top picks with you.",
      isFeatured: false,
    },
    {
      author: "John Smith",
      category: "travel",
      excerpt: "Discover the best hidden gems in Europe with our ultimate travel guide. From quaint towns to stunning natural landscapes, we've got you covered.",
      image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8dHJhdmVsfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Ultimate Guide to Hidden Gems in Europe",
      first_content: "Are you tired of visiting the same old tourist traps? Look no further than our ultimate guide to hidden gems in Europe. From charming towns to breathtaking natural wonders, we've scoured the continent to bring you the best of the best. Whether you're an avid hiker or a history buff, there's something for everyone on this list.",
      second_content: "Take a stroll through the picturesque streets of Giethoorn in the Netherlands, or marvel at the stunning Cliffs of Moher in Ireland. If you're looking for a more off-the-beaten-path adventure, explore the unique architecture of Riga, Latvia, or soak in the thermal waters of the Blue Lagoon in Iceland. With our guide, you'll discover a side of Europe that most tourists never see.",
      isFeatured: true
    },
    {
      author: "Jane Doe",
      category: "food",
      excerpt: "From mouthwatering pizza to indulgent gelato, Italian cuisine is known for its bold flavors and fresh ingredients. Get ready to discover the best Italian dishes you've ever tasted!",
      image: "https://images.unsplash.com/photo-1519681393784-d120267933ba?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=80",
      title: "A Food Lover's Guide to Italy",
      first_content: "If you're a food lover, there's no better destination than Italy. From pizza to pasta to gelato, this country is home to some of the world's most iconic dishes. But with so many options, where do you start? That's where we come in. Our guide will take you on a culinary journey through Italy, highlighting the best dishes in each region.",
      second_content: "Indulge in the rich flavors of Tuscany with a hearty bowl of ribollita, or savor the seafood specialties of Sicily with a plate of pasta alla norma. And of course, no trip to Italy is complete without trying the world-famous Neapolitan pizza. With our guide, you'll discover new flavors and culinary traditions that will leave your taste buds begging for more.",
      isFeatured: false
    },
    {
      author: "David Lee",
      category: "health",
      excerpt: "Whether you're looking to lose weight, build muscle, or simply improve your overall health, our fitness guide has everything you need to get started.",
      image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGhlYWx0aHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Ultimate Fitness Guide for Beginners",
      first_content: "Starting a new fitness routine can be overwhelming, especially if you're not sure where to begin. That's why we've created the ultimate fitness guide for beginners. Our guide covers everything from setting realistic goals to choosing the right workout plan for your needs.",
      second_content: "Learn how to fuel your body with healthy, nutritious foods, and discover the best exercises for building strength and endurance. Whether you prefer to work out at home or at the gym, our guide has plenty of tips and advice to help you reach your fitness goals. With our step-by-step plan, you'll be on your way to a healthier, happier you in no time.",
      isFeatured: true
    },
    {
      author: "Shannan Shapter",
      category: "fashion",
      excerpt: "Looking for the perfect gift for the men in your life this holiday season? Look no further than our great big list of gift ideas! From stylish clothing to cutting-edge gadgets, we've got you covered.",
      image: "https://images.unsplash.com/photo-1537832816519-689ad163238b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fGZhc2hpb258ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
      title: "The Great Big List of Men’s Gifts for the Holidays",
      first_content: "If you're struggling to come up with gift ideas for the men in your life, you're not alone. It can be tough to find the perfect present that's both thoughtful and practical. That's why we've put together this great big list of gift ideas that are sure to impress. Whether you're shopping for your dad, brother, boyfriend, or husband, we've got you covered. From stylish clothing to cutting-edge gadgets, there's something for everyone on your list.",
      second_content: "So what are you waiting for? Start browsing our list of gift ideas today and find the perfect present for the men in your life. And don't forget to check out our expert tips and advice on how to choose the perfect gift. Happy shopping!",
      isFeatured: false,
    },
    {
      author: "David Chen",
      category: "technology",
      excerpt: "From smartphones to laptops, discover the latest and greatest tech products of the year. We’ve rounded up the top 5 products that are worth the investment.",
      image: "https://images.unsplash.com/photo-1512686096451-a15c19314d59?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dGVjaCUyMHByb2R1Y3RzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "Top 5 Must-Have Tech Products of the Year",
      first_content: "Are you a tech enthusiast looking for the latest and greatest gadgets? Look no further than our list of the top 5 must-have tech products of the year. From cutting-edge smartphones to powerful laptops, these products are worth the investment.",
      second_content: "We’ve tested and reviewed each product to ensure that they meet our high standards for quality and innovation. So whether you’re a gamer, a photographer, or simply looking for a device that can keep up with your busy lifestyle, these products are sure to impress.",
      isFeatured: true,
    },
    {
    author: "John Smith",
    category: "technology",
    excerpt: "Artificial intelligence is changing the world we live in. From self-driving cars to voice assistants, AI is transforming the way we interact with technology. But what does the future hold for this powerful technology? In this article, we explore the potential impact of AI on society and the economy.",
    image: "https://images.unsplash.com/photo-1591696331111-ef9586a5b17a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTF8fGFydGlmaWNpYWwlMjBpbnRlbGxpZ2VuY2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    title: "The Future of AI: Opportunities and Challenges",
    first_content: "Artificial intelligence is no longer the stuff of science fiction. It is now a part of our daily lives, from the voice assistants on our smartphones to the algorithms that power our social media feeds. As AI continues to evolve, it has the potential to transform the world we live in. However, it also presents a number of challenges and risks.",
    second_content: "One of the key challenges of AI is the potential impact on employment. As machines become more intelligent, they may be able to perform tasks that were previously done by humans. This could lead to widespread job displacement and economic disruption. Additionally, there are concerns about the impact of AI on privacy, security, and civil liberties. As AI becomes more pervasive, it may become more difficult to protect our personal data and ensure that our rights are respected.",
    isFeatured: true,
    },
    {
      author: "Sara Lee",
      category: "food",
      excerpt: "Trying to eat healthier can be tough, but there are simple changes you can make to your diet that can have a big impact. In this article, we share our top tips for eating healthy, including incorporating more fruits and vegetables into your meals, choosing whole grains, and limiting processed foods.",
      image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OHx8Zm9vZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "10 Simple Tips for Eating Healthier",
      first_content: "If you're looking to improve your diet, start by making small changes. One easy way to eat healthier is to incorporate more fruits and vegetables into your meals. Aim for a variety of colors to get a range of nutrients. Another tip is to choose whole grains instead of refined grains, which are stripped of important nutrients.",
      second_content: "Processed foods are often high in salt, sugar, and unhealthy fats, so it's best to limit these foods as much as possible. Instead, try cooking at home more often and using fresh ingredients. And don't forget to stay hydrated! Drinking plenty of water is essential for good health.",
      isFeatured: true,
    },
    {
      author: "Maria Rodriguez",
      category: "travel",
      excerpt: "Traveling is one of life's great pleasures, but it can be expensive. In this article, we share our top tips for traveling on a budget, including choosing affordable destinations, traveling during the off-season, and using rewards programs to save money on flights and hotels.",
      image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
      title: "How to Travel on a Budget: Tips and Tricks",
      first_content: "One of the easiest ways to save money on travel is to choose affordable destinations. There are plenty of beautiful places to visit that won't break the bank, such as Southeast Asia, Eastern Europe, and Central America. Another tip is to travel during the off-season, when prices are typically lower and crowds are thinner.",
      second_content: "To save money on flights and hotels, consider signing up for rewards programs. Many airlines and hotel chains offer loyalty programs that allow you to earn points or miles that can be redeemed for free or discounted travel. And don't forget to be flexible with your travel plans - by being open to different dates and times, you may be able to find better deals.",
      isFeatured: false,
    },
    {
      author: "David Brown",
      category: "business",
      excerpt: "Leadership is a critical component of success in business. In this article, we explore the qualities of effective leaders, including the ability to inspire and motivate others, the willingness to take risks, and the capacity for strategic thinking.",
      image: "https://images.unsplash.com/photo-1664575600796-ffa828c5cb6e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGJ1c2luZXNzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60",
      title: "The Qualities of Effective Leaders",
      first_content: "Effective leaders have a number of key qualities that set them apart from others. One of the most important is the ability to inspire and motivate others. Great leaders are able to communicate their vision and get others excited about working toward a common goal. They are also willing to take risks and make bold decisions, even in the face of uncertainty.",
      second_content: "Another important quality of effective leaders is the capacity for strategic thinking. They are able to see the big picture and develop a long-term plan for success. And they are not afraid to make tough decisions or pivot when necessary. Finally, great leaders lead by example, setting a high standard for themselves and their team.",
      isFeatured: false,
    },
    {
      author: "Emma Davis",
      category: "travel",
      excerpt: "If you're looking for an unforgettable beach vacation in Southeast Asia, you're in luck. Our top 10 beaches to visit will take you to some of the most stunning destinations in the region. From pristine white sands to crystal clear waters, these beaches offer the perfect getaway for any traveler.",
      image: "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYXZlbHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60",
      title: "Top 10 Beaches to Visit in Southeast Asia",
      first_content: "Our top pick for the best beach in Southeast Asia is the stunning Maya Bay in Thailand. With its clear turquoise waters and towering limestone cliffs, it's a true paradise for beachgoers. Other highlights include the gorgeous beaches of Bali, Indonesia, where you can surf, swim, and soak up the sun, and the secluded shores of Palawan, Philippines, which offer a peaceful escape from the crowds.",
      second_content: "If you're looking for something off the beaten path, consider visiting the beaches of Koh Rong, Cambodia, which are known for their untouched natural beauty. Or head to the island of Phu Quoc in Vietnam, where you can relax on the quiet beaches and explore the vibrant local culture. No matter where you choose to go, Southeast Asia is home to some of the world's most beautiful beaches, and we're excited to share our top picks with you.",
      isFeatured: false,
    }
  ]
};

export default data;